### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'VB_result2/tmp/VB_hmmer.out'

### ISSUE THREAD

**Issue by yujieWang2** [GreyGuoweiChen/RNA_virus_detector#9]
(virbot) wangyujie@wangyujie-Vostro-3681:/media/wangyujie/文件/RNA Virus2$ VirBot.py --input all.ref_denovo.viral.contig.fa --output VB_result2 --sen
Input contig: all.ref_denovo.viral.contig.fa
Output directory: VB_result2
Mode: sensitive mode
Predicting the encoded proteins...
Proteins prediction finished.
Scanning the protein by hmmsearch...
HMMER finshed.
Scanning the protein by DIAMOND...
DIAMOND finshed.
Num of proteins 124
Traceback (most recent call last):
  File "/media/wangyujie/文件/RNA Virus2/RNA_virus_detector/VirBot.py", line 375, in &lt;module&gt;
    predict(output_dir=f"{output_dir}/",
  File "/media/wangyujie/文件/RNA Virus2/RNA_virus_detector/VirBot.py", line 313, in predict
    proteins = parse_hmmsearch(temp_dir + "VB_hmmer.out", proteins)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/wangyujie/文件/RNA Virus2/RNA_virus_detector/VirBot.py", line 184, in parse_hmmsearch
    with open(filename,'r') as f:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'VB_result2/tmp/VB_hmmer.out'

I have encountered some issues and hope to receive your reply

**Comment by GreyGuoweiChen** [comment]
Hello Yujie,

According to your message, the proteins are translated correctly, but HMMER does not output the match result. This may result from the absence of the availble HMMER pacakge. I highly suggest you to check the availability of HMMER.

You could type the command below in your environment to check.
`hmmsearch `
If it is valid, the outpur should be:
```
Incorrect number of command line arguments.
Usage: hmmsearch [options] <hmmfile> <seqdb>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h
```

Otherwise, it will output:
`bash: hmmsearch: command not found...`
And then please install hmmer, by
`conda install -c bioconda hmmer`
